services:
  - type: web
    name: guvi-final
    env: php
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000"
    plan: free
    databases:
      - name: mydb

databases:
  - name: mydb
    plan: free
